version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "4200:4200"
      - "4040:4040"
      - "8081:8081"
    links:
      - mongo
    depends_on:
      - mongo 
    volumes:
      - ./:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
